export const chessDefault = [
  [
    {side: 0, role: 'ju', name: '車'},
    {side: 0, role: 'ma', name: '馬'},
    {side: 0, role: 'xiang', name: '相'},
    {side: 0, role: 'shi', name: '仕'},
    {side: 0, role: 'jiang', name: '帥'},
    {side: 0, role: 'shi', name: '仕'},
    {side: 0, role: 'xiang', name: '相'},
    {side: 0, role: 'ma', name: '馬'},
    {side: 0, role: 'ju', name: '車'},
  ],
  [null, null, null, null, null, null, null, null, null],
  [
    null,
    {side: 0, role: 'pao', name: '炮'},
    null,
    null,
    null,
    null,
    null,
    {side: 0, role: 'pao', name: '炮'},
    null
  ],
  [
    {side: 0, role: 'bing', name: '兵'},
    null,
    {side: 0, role: 'bing', name: '兵'},
    null,
    {side: 0, role: 'bing', name: '兵'},
    null,
    {side: 0, role: 'bing', name: '兵'},
    null,
    {side: 0, role: 'bing', name: '兵'},
  ],
  [null, null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null, null],
  [
    {side: 1, role: 'bing', name: '卒'},
    null,
    {side: 1, role: 'bing', name: '卒'},
    null,
    {side: 1, role: 'bing', name: '卒'},
    null,
    {side: 1, role: 'bing', name: '卒'},
    null,
    {side: 1, role: 'bing', name: '卒'},
  ],
  [
    null,
    {side: 1, role: 'pao', name: '砲'},
    null,
    null,
    null,
    null,
    null,
    {side: 1, role: 'pao', name: '砲'},
    null
  ],
  [null, null, null, null, null, null, null, null, null],
  [
    {side: 1, role: 'ju', name: '車'},
    {side: 1, role: 'ma', name: '馬'},
    {side: 1, role: 'xiang', name: '象'},
    {side: 1, role: 'shi', name: '士'},
    {side: 1, role: 'jiang', name: '將'},
    {side: 1, role: 'shi', name: '士'},
    {side: 1, role: 'xiang', name: '象'},
    {side: 1, role: 'ma', name: '馬'},
    {side: 1, role: 'ju', name: '車'},
  ],
]